(package "auto-close-tag" "0.0.1" "Automatically add HTML/XML close tag.")

(website-url "https://github.com/jcs-elpa/auto-close-tag")
(keywords "convenience" "keybindings")

(package-file "auto-close-tag.el")

(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
